export const baseURL = 'http://localhost:8000/api/v1'
export const siteAPI = baseURL + '/site/'
export const crawlerAPI = baseURL + '/crawler/'
export const indexerAPI = baseURL + '/indexer/'
export const sitePagesAPI = baseURL + '/page?siteId='
export const pageAPI = baseURL + '/page/'
export const siteErrorsAPI = baseURL + '/error?siteId='
export const errorAPI = baseURL + '/error/'